### ISSUE TITLE
example script from README not working...

### ISSUE THREAD

**Issue by Donkere-vader** [ahmedkhalf/Circle-Evolution#13]
**The bug**
When running your script from the command line like:
```circle_evolution "Mona Lisa 128.jpg" --size 1 --max-generation 5000```
The program works just fine.

*but* when run with the python script (from the README) I only get like the first generation (I think that is what I get; 5 grey circles)

**Screenshot**
![alt text](https://i.imgur.com/ZP9tZCn.png)

**System**
 - OS: Pop!_os 20.04 (based on Ubuntu)
 - Version 0.1
 - Python version 3.8

**Comment by guimorg** [comment]
Hi, @Donkere-vader!

Thank you for the info on the bug, I've just looked into the problem and I will solve it right away. 

The problem is related to the number of genes, the default number is only 5, that means that it will try solving the objective function using 5 circles (that's why you see 5 circles on the image).

I'll fix the `README.md` file and also the default number of circles! You can always play with that number to obtain smoother images!

In the meantime, you can try

```python
from circle_evolution import evolution
from circle_evolution import helpers
import numpy as np
import cv2

target = helpers.load_target_image("Mona Lisa 64.jpg", size=(64, 64))
e = evolution.Evolution((64, 64), target, genes=256)

e.evolve(max_generation=50000)

helpers.show_image(e.specie.phenotype)

np.savetxt("Checkpoint.txt", e.specie.genotype)
cv2.imwrite("OuputImage.jpg", e.specie.phenotype)
```

I'll wait for your response to close the issue! Thank you for the feedback again!

**Comment by Donkere-vader** [comment]
This fixed the issue! Thanks!
