### ISSUE TITLE
Support for non-square images

### ISSUE THREAD

**Issue by Lucas-C** [ahmedkhalf/Circle-Evolution#16]
**Is your feature request related to a problem? Please describe.**
It seems to be that `circle_evolution` currently can only produce square images.
Could it be modified to also generates rectangular ones if the source image is non-square ?

**Describe the solution you'd like**
Handle rectangular images.

**Describe alternatives you've considered**
I admit I haven't. This is just a suggestion for an improvement :)

**Additional context**
None really, but thanks a lot for releasing this tool as an open-souce project !
And good job on the code, it is quite clear 👍

**Comment by ahmedkhalf** [comment]
Hi Lucas!
We already have support for non-square images by using python code:
```python
from circle_evolution import evolution
from circle_evolution import helpers
import numpy as np
import cv2


target = helpers.load_target_image("filename.jpg", size=(92, 64))
# You can put whatever size you like here:       ^^^^^^^^^^^^^^^^^
e = evolution.Evolution((92, 64), target, genes=256)
# and here:       ^^^^^^^^^^^^^^^^^

e.evolve(max_generation=50000)

helpers.show_image(e.specie.phenotype)

np.savetxt("Checkpoint.txt", e.specie.genotype)
cv2.imwrite("OuputImage.jpg", e.specie.phenotype)
```
However we currently don't support it in our cli, this will hopefully get fixed by next release, (you can start a pull request to fix it if you would like to contribute).

Anyways, here is a sneak peek of the next release:
![github](https://user-images.githubusercontent.com/36672196/83172679-ff2b1a00-a128-11ea-94d9-34948ad47df0.png)
